

url: https://cs302.org
base_path: /sp26
semester: Spring 2026

title: CS 302 | Spring 2026
author: Michael Ball, Dan Garcia
description: Designing Computer Science Education

# markdown: rdiscount

staff:
  - name: Michael Ball
    image: images/michael.jpg
    pronouns: he/him
    email: ball@berkeley.edu
    role: co-instructor
  - name: Dan Garcia
    image: images/dan.jpg
    pronouns: he/him
    email: ddgarcia@berkeley.edu
    role: co-instructor
  - name: Victor Huang
    image: images/victor.jpg
    pronouns: he/him
    email: vortic@berkeley.edu
    role: reader

# This should be shared view-only just to students.
google_drive_folder: https://drive.google.com/drive/u/1/folders/1XEpWDYJSL6P1JKPMms6YdhBLAC37PsyG
